### ISSUE TITLE
Version 0.16.0 not on marketplace

### ISSUE THREAD

**Issue by bric3** [FirstTimeInForever/intellij-pdf-viewer#109]
Hi there, I noticed the latest version is not available on the marketplace, is there any reason for this ?

**Comment by PHPirates** [comment]
I am aware of the issue, I have tried to contact @FirstTimeInForever to upload the new version but so far no luck.

**Comment by PHPirates** [comment]
I know, the issue is currently he is the only one with permission to upload.

**Comment by bric3** [comment]
Ah too bad, I hope @FirstTimeInForever is well and could reply. He seems to be @JetBrains so maybe they can help there.

**Comment by FirstTimeInForever** [comment]
Hey folks! I'm really sorry for being missing for some now, I have too much stuff going on for some time now and can't really spend any time on my open-source projects.

@PHPirates I think something went wrong with the pre-release -> release -> upload workflow, I've submitted the version from the `0.16.0` release manually. I'll see if I can somehow make it possible to do the upload without my involvement, since it has been proven not to be very reliable :)

**Comment by FirstTimeInForever** [comment]
@PHPirates I've added you as a developer for the plugin on the Marketplace, so you should be able to upload the new versions.

**Comment by PHPirates** [comment]
@FirstTimeInForever  Thanks so much! No worries, really appreciate all the work you have put in this plugin. We will make sure to keep it working.
Yeah the github action for releases to github did not work anymore, fixed that in #104 already. Will have a look to upload to the marketplace as well, that would be nice.
