### ISSUE TITLE
Renders PDF view over 'undocked' tool windows

### ISSUE THREAD

**Issue by hugoppp** [FirstTimeInForever/intellij-pdf-viewer#12]
The PDF view is rendered above tool windows which are set to 'undocked' view mode (right click → view mode).

Notice in the screenshot the structure tool window is in 'docked' view mode, that's why the seam is in the middle of the tool window. If there is no tool window in docked mode, the whole undocked tool window is covered.
![screenshot](https://i.imgur.com/TBmQdrN.png)

**Comment by FirstTimeInForever** [comment]
Thank you for reporting this issue! Can you check if the markdown preview has the same behaviour? Can you you also provide the IDE version that you are using?

**Comment by hugoppp** [comment]
>Can you check if the markdown preview has the same behaviour
I'll check once I can, I'm pretty busy right now.

This is my version info:
>IntelliJ IDEA 2020.2.3 (Ultimate Edition)
Build #IU-202.7660.26, built on October 6, 2020
Runtime version: 11.0.8+10-b944.34 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12
Registry: documentation.show.toolbar=true, ide.tree.collapse.recursively=false, ide.balloon.shadow.size=0, pdf.viewer.enableExperimentalFeatures=true
Non-Bundled Plugins: IdeaVIM, PlantUML integration, com.firsttimeinforever.intellij.pdf.viewer.intellij-pdf-viewer, SpellChecker, SpellChecker-Dict-English, SpellChecker-Dict-German, String Manipulation, de.docksnet.puml.syntaxchecker, ru.leoklo.stackuml, com.tabnine.TabNine, com.vincentp.gruvbox-theme, de.santiv.fastscrolling, org.jetbrains.erlang, zielu.gittoolbox, com.almightyalpaca.intellij.plugins.discord, mobi.hsz.idea.gitignore, com.jetbrains.codeWithMe, org.plugin.dot.id, some.awesome, org.jetbrains.kotlin, com.jetbrains.edu, training, nl.rubensten.texifyidea

**Comment by FirstTimeInForever** [comment]
It seems like this is an issue in the IntelliJ platform. Currently, JCEF (the one in JBR) is quite a bit broken and there are a lot of issues related to JCEF windows overlapping UI posted on the JetBrains issue tracker.
I can't say that this issue will be fixed in the current IDEA release (as it is still present in `2020.3`). I will keep an eye on the 

Funny enough, PDF Viewer works fine in the latest `2020.3`, but markdown preview is struggling. (PDF Viewer preview is pretty much identical to the one in the bundled markdown plugin, so if the latter is broken, PDF viewer will be broken too).

For the reference:
https://youtrack.jetbrains.com/issue/IDEA-253745

**Comment by PHPirates** [comment]
I undocked a tool window and this issue appears to have been fixed:

![image](https://user-images.githubusercontent.com/15669080/235987078-94bed28c-c695-40e6-9eb1-686333e7f105.png)
