### ISSUE TITLE
"Invalid or Corrupted PDF file" sometimes on successful LaTeX compile, refresh button does not work

### ISSUE THREAD

**Issue by kalekje** [FirstTimeInForever/intellij-pdf-viewer#37]
As the title states, I often get the red "Invalid or Corrupted PDF file"  message on the pdf if I leave it open during a LaTeX compile. After hitting refresh, it does nothing. I have to manually exit the pdf file's tab and re-open it for it it to display properly.

**Comment by PHPirates** [comment]
Which version of the plugin? You may try the latest alpha version, I haven't seen the issue with the alpha version at least.

**Comment by kalekje** [comment]
I'm using v 0.12-alpha.4 on Windows

**Comment by burkeg** [comment]
I am also experiencing this issue with plugin version 0.14.0.

PyCharm 2021.3.3 (Community Edition)
Build #PC-213.7172.26, built on March 15, 2022
Runtime version: 11.0.14.1+1-b1751.46 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2042M
Cores: 16
Non-Bundled Plugins:
    nl.rubensten.texifyidea (0.7.15)
    com.firsttimeinforever.intellij.pdf.viewer.intellij-pdf-viewer (0.14.0)
    ru.meanmail.plugin.requirements (2022.3-2021.3)

**Comment by dmibuch** [comment]
> I am also experiencing this issue with plugin version 0.14.0.
> 
> PyCharm 2021.3.3 (Community Edition) Build #PC-213.7172.26, built on March 15, 2022 Runtime version: 11.0.14.1+1-b1751.46 amd64 VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o. Windows 10 10.0 GC: G1 Young Generation, G1 Old Generation Memory: 2042M Cores: 16 Non-Bundled Plugins: nl.rubensten.texifyidea (0.7.15) com.firsttimeinforever.intellij.pdf.viewer.intellij-pdf-viewer (0.14.0) ru.meanmail.plugin.requirements (2022.3-2021.3)

So do I.
Manjaro Linux, GNOME 41.4, Wayland, Intellij Idea 2021.3.2 Community Edition. Plugin version 0.14.0.

**Comment by burkeg** [comment]
@dmibuch As a workaround I added the arguments "-halt-on-error -output-directory temp_dir" to the pdflatex command and only copied the .pdf from the temp_dir if pdflatex returned with exit code 0 so the pdf I had open in the IDE would never be corrupted.

**Comment by Kamest** [comment]
Same in 

DataSpell 2021.3.3
Build #DS-213.7172.29, built on March 17, 2022
Runtime version: 11.0.14.1+1-b1751.46 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.13.0-39-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 16
Registry:
    ide.intellij.laf.enable.animation=true
    ide.balloon.shadow.size=0
    python.scientific.show_help_window=false
    python.scientific.always_use_sci_view=true

Non-Bundled Plugins:
    tanvd.grazi (213.7172.5)
    com.mallowigi.idea (16.0)
    com.jetbrains.sh (213.5744.121)
    com.jetbrains.plugins.ini4idea (213.5744.190)
    com.intellij.plugins.watcher (213.6461.19)
    nl.rubensten.texifyidea (0.7.15)
    com.intellij.ideolog (203.0.27.0)
    com.firsttimeinforever.intellij.pdf.viewer.intellij-pdf-viewer (0.14.0)
    Key Promoter X (2021.3)

Current Desktop: ubuntu:GNOME

and plugin version 0.14.0. But I think there ain't any workaround in Dataspell for now.

**Comment by jandermoreira** [comment]
Same problem with version 0.14.0 in IntelliJ IDEA 2022.1.1 (Community Edition), Debian 11, GNOME Shell 3.38.6.

**Comment by ekhahniii** [comment]
> @dmibuch As a workaround I added the arguments "-halt-on-error -output-directory temp_dir" to the pdflatex command and only copied the .pdf from the temp_dir if pdflatex returned with exit code 0 so the pdf I had open in the IDE would never be corrupted.

@burkeg Was this workaround accomplished only by modifying the run configuration? Wondering if you could provide guidance, especially for how you handled copying iff successful compilation.

**Comment by ekhahniii** [comment]
The following is a no frills workaround inspired by @burkeg's [previous response](https://github.com/FirstTimeInForever/intellij-pdf-viewer/issues/37#issuecomment-1073354113).

Given the following:
- a LaTeX project
- a functioning Run Configuration, e.g. called `manuscript`
- [built in PDF viewer](https://github.com/Hannah-Sten/TeXiFy-IDEA/wiki/Built-in-pdf-viewer-support) is used for viewing and `Settings > Other Settings > PDF Viewer > General > Reload on document change` is enabled (by default).

Then:
1. Create a directory `tmp` (e.g. beside or within the default `out` directory into which the generated PDF is currently written).
2. Create a script (e.g. `move.py` beside `tmp`) that moves the generated PDF from `tmp` to `out`.
```python
import shutil
from pathlib import Path

path_tmp_pdf = Path(__file__).parent / 'tmp' / 'manuscript.pdf'
path_out_pdf = Path(__file__).parent / 'out' / 'manuscript.pdf'

if path_out_pdf.exists():
    path_out_pdf.unlink()
shutil.move(path_tmp_pdf, path_out_pdf)
```
3. In the Run Configuration of `move.py`, under `Before Launch`, click `+` and select the already existing `manuscript` Run Configuration. 
![image](https://user-images.githubusercontent.com/49728874/214748750-18a2a5f7-fb59-4f1c-afd1-679621b7b317.png)
4. In the Run Configuration of `manuscript`, under `PDF viewer`, choose "No PDF viewer".
5. In the Run Configuration of `manuscript`, under `Directory for output files, ...`, overwrite with the path to `tmp`.

Running `move.py` will:
1. Run `manuscript` to compile and write the PDF to `tmp`.
2. Run `move.py` to move the PDF from `tmp` to `out`. 
3. Implicitly trigger PDF viewer to reload the PDF file in `out`.

If the PDF in `out` (not `tmp) is open in a tab via PDF viewer, the file move will trigger PDF viewer to reload the PDF. Because the source and destination of the move are (presumably) on the same file system, the move should be atomic and prevent the viewer from ever seeing an empty file and erroring out. This should avoid [the issue](https://github.com/FirstTimeInForever/intellij-pdf-viewer/issues/37) noted by @kalekje.

**Comment by ReHoss** [comment]
Any news ? Texify is broken then?

**Comment by PHPirates** [comment]
The original description is not quite clear, but this issue occurs when you:

* Start compilation
* Transfer focus away from IntelliJ
* Focus the PDF editor, exception occurs
* Compilation finishes

So the workaround is clear: just keep your focus in IntelliJ during compilation.

Maybe @slideclimb can check if we can catch and ignore this `Invalid PDF structure.` exception, since it's an expected situation.

**Comment by ReHoss** [comment]
@PHPirates the issue is here even when I 

with @ekhahniii workaround we lose the ctrl+click feature...

I cannot use the LaTeX plugin anymore.
