### ISSUE TITLE
No option to hide thumbnails

### ISSUE THREAD

**Issue by imashnake0** [FirstTimeInForever/intellij-pdf-viewer#95]
I don't see an option to hide thumbnails and they take up a lot of the width:
<img width="404" alt="Screen Shot 2024-04-06 at 11 27 28 PM" src="https://github.com/FirstTimeInForever/intellij-pdf-viewer/assets/56754616/b68e6542-0758-4732-a5ee-3146f821d587">

Add menu for PDF viewer options.

**Comment by imashnake0** [comment]
Found it in Preferences > PDF Viewer.

**Comment by W-L** [comment]
Running into the same issue. Reinstalled Jetbrains tools and plugins and now the button to toggle the thumbnail/structure sidebar is gone. In the preferences it's only possible to toggle the default behaviour for me (thanks for the hint), but not to restore the toolbar buttons. Do you know if there is a way to bring that button back?
(also, would you mind reopening the issue? Could also create a new one otherwise.)

**Comment by Dragonwick** [comment]
I do not see any option not get rid of the thumbnails, I have tried uninstalling and reinstalling. No luck.

**Comment by W-L** [comment]
can confirm, that version of the plugin brings back the button for the sidebar options on my setup :+1:

**Comment by PHPirates** [comment]
Thanks! Then we'll try to get out a new release
